// src/lib/tools-registry.ts
// ─────────────────────────────────────────────────────────────────────────────
// CENTRAL TOOL REGISTRY
// Add a new tool here and it auto-gets: SEO page, category listing,
// related-tools widget, sitemap entry, and blog suggestions.
// ─────────────────────────────────────────────────────────────────────────────

export type ToolCategory =
  | 'developer'
  | 'text'
  | 'seo'
  | 'image'
  | 'pdf'
  | 'converter';

export type WorkspaceCategory =
  | 'frontend-tools'
  | 'backend-api'
  | 'devops-ci-cd'
  | 'testing'
  | 'code-editors-ide'
  | 'package-managers'
  | 'ui-ux-design'
  | 'performance-seo'
  | 'security'
  | 'ai-developer';

export interface ToolDefinition {
  slug: string;          // URL slug: /tools/{category}/{slug}
  category: ToolCategory;
  name: string;          // Display name
  tagline: string;       // Short tagline used in cards
  description: string;   // Longer description for SEO meta
  h1: string;            // H1 heading on the tool page
  metaTitle: string;     // <title> tag
  metaDescription: string;
  keywords: string[];
  icon: string;          // emoji icon
  component: string;     // React component filename (no extension)
  popular?: boolean;
  new?: boolean;
  relatedSlugs?: string[];
  faq?: { q: string; a: string }[];
}

export interface Tool extends ToolDefinition {
  workspaceCategory: WorkspaceCategory;
}

export const TOOL_DEFINITIONS: ToolDefinition[] = [
  // ── DEVELOPER ──────────────────────────────────────────────────────────────
  {
    slug: 'json-formatter',
    category: 'developer',
    name: 'JSON Formatter',
    tagline: 'Format, beautify & validate JSON instantly',
    description: 'Free online JSON formatter and validator. Beautify minified JSON, fix errors, and explore your data with syntax highlighting.',
    h1: 'JSON Formatter Tool (Free & Online)',
    metaTitle: 'Free JSON Formatter Online – Fast, Secure & No Signup',
    metaDescription: 'Format and beautify JSON instantly with our free online JSON formatter. Validate JSON errors, syntax highlight, and minify – no signup required.',
    keywords: ['json formatter', 'json beautifier', 'json validator', 'format json online', 'pretty print json'],
    icon: '{}',
    component: 'JSONFormatter',
    popular: true,
    relatedSlugs: ['json-minify', 'base64-encode', 'html-formatter'],
    faq: [
      { q: 'What is a JSON formatter?', a: 'A JSON formatter (also called a JSON beautifier) takes compact or minified JSON and adds proper indentation, line breaks, and spacing to make it human-readable.' },
      { q: 'Is this JSON formatter free?', a: 'Yes, completely free with no registration required. All processing happens in your browser — your data never leaves your device.' },
      { q: 'Can it validate JSON errors?', a: 'Yes. The formatter highlights syntax errors and tells you exactly which line and character is causing the problem.' },
      { q: 'What is the maximum file size?', a: 'There is no hard limit since processing is client-side, but very large files (50MB+) may be slow depending on your device.' },
    ],
  },
  {
    slug: 'json-minify',
    category: 'developer',
    name: 'JSON Minify',
    tagline: 'Strip whitespace from JSON to reduce file size',
    description: 'Minify and compress JSON by removing all unnecessary whitespace. Perfect for production APIs and reducing payload sizes.',
    h1: 'JSON Minifier / Compressor (Free Online)',
    metaTitle: 'JSON Minify Online – Compress & Minify JSON Free',
    metaDescription: 'Minify JSON by removing whitespace and comments. Reduce JSON file size instantly — free, fast, and no signup needed.',
    keywords: ['json minify', 'json compress', 'minify json online', 'json uglify'],
    icon: '⚡',
    component: 'JSONMinify',
    relatedSlugs: ['json-formatter', 'base64-encode'],
    faq: [
      { q: 'What does JSON minify do?', a: 'It removes all unnecessary whitespace (spaces, tabs, newlines) from JSON, reducing the file size without changing the data structure.' },
      { q: 'Why minify JSON?', a: 'Minified JSON is faster to transfer over networks and reduces bandwidth costs for APIs and web applications.' },
    ],
  },
  {
    slug: 'base64-encode',
    category: 'developer',
    name: 'Base64 Encode / Decode',
    tagline: 'Encode and decode Base64 strings instantly',
    description: 'Free online Base64 encoder and decoder. Convert text or files to Base64 and back. Supports UTF-8 strings and binary data.',
    h1: 'Base64 Encode & Decode Tool (Free Online)',
    metaTitle: 'Base64 Encoder Decoder Online – Free & Instant',
    metaDescription: 'Encode text or files to Base64 and decode Base64 strings back to plain text. Free, instant, no signup — works entirely in your browser.',
    keywords: ['base64 encode', 'base64 decode', 'base64 encoder', 'base64 decoder online', 'encode base64'],
    icon: '🔐',
    component: 'Base64Tool',
    popular: true,
    relatedSlugs: ['url-encoder', 'jwt-decoder', 'html-viewer'],
    faq: [
      { q: 'What is Base64 encoding?', a: 'Base64 is a binary-to-text encoding scheme that represents binary data using 64 ASCII characters. It\'s widely used in email attachments, data URLs, and API authentication.' },
      { q: 'Is Base64 the same as encryption?', a: 'No. Base64 is encoding, not encryption. It\'s easily reversible and provides no security. Never use it to hide sensitive data.' },
      { q: 'Can I encode files with this tool?', a: 'Yes. Use the "File" tab to upload any file and get its Base64 representation, useful for embedding images in CSS or HTML.' },
    ],
  },
  {
    slug: 'html-viewer',
    category: 'developer',
    name: 'HTML Viewer',
    tagline: 'Preview HTML code in real-time in your browser',
    description: 'Free online HTML viewer with live preview. Paste HTML code and see it rendered instantly. Great for testing snippets and email templates.',
    h1: 'HTML Viewer & Live Preview Tool (Free Online)',
    metaTitle: 'HTML Viewer Online – Live Preview HTML Code Free',
    metaDescription: 'Preview HTML code instantly in your browser. Paste any HTML and see a live rendered preview — free online HTML viewer, no signup required.',
    keywords: ['html viewer', 'html preview', 'html renderer online', 'live html preview', 'test html online'],
    icon: '</> ',
    component: 'HTMLViewer',
    popular: true,
    relatedSlugs: ['html-formatter', 'json-formatter', 'base64-encode'],
    faq: [
      { q: 'What is an HTML viewer?', a: 'An HTML viewer renders raw HTML code as a visual web page, so you can see exactly how it would look in a browser without creating a file.' },
      { q: 'Can I test JavaScript in the HTML viewer?', a: 'Yes. The live preview renders HTML, CSS, and JavaScript just like a browser would.' },
      { q: 'Is this tool safe for sensitive HTML?', a: 'All rendering happens locally in your browser using a sandboxed iframe. No code is sent to any server.' },
    ],
  },
  {
    slug: 'html-formatter',
    category: 'developer',
    name: 'HTML Formatter',
    tagline: 'Beautify and indent HTML code automatically',
    description: 'Format and beautify messy HTML with proper indentation. Great for cleaning up code from editors or CMS exports.',
    h1: 'HTML Formatter & Beautifier (Free Online)',
    metaTitle: 'HTML Formatter Online – Beautify & Indent HTML Free',
    metaDescription: 'Beautify and format HTML code online with proper indentation. Clean up messy HTML in one click — free, no signup required.',
    keywords: ['html formatter', 'html beautifier', 'format html online', 'indent html', 'html pretty print'],
    icon: '🎨',
    component: 'HTMLFormatter',
    relatedSlugs: ['html-viewer', 'json-formatter'],
    faq: [
      { q: 'What does HTML formatting do?', a: 'It adds consistent indentation and line breaks to HTML, making it easier to read and maintain.' },
    ],
  },
  {
    slug: 'url-encoder',
    category: 'developer',
    name: 'URL Encoder / Decoder',
    tagline: 'Encode and decode URL components instantly',
    description: 'Encode special characters in URLs and decode percent-encoded strings. Essential for working with query parameters and API calls.',
    h1: 'URL Encoder & Decoder Tool (Free Online)',
    metaTitle: 'URL Encoder Decoder Online – Percent Encode URLs Free',
    metaDescription: 'Encode and decode URLs and query string parameters online. Convert special characters to percent encoding — free, instant, no signup.',
    keywords: ['url encoder', 'url decoder', 'percent encode url', 'url encode online', 'decode url online'],
    icon: '🔗',
    component: 'URLEncoderDecoder',
    relatedSlugs: ['base64-encode', 'jwt-decoder'],
    faq: [
      { q: 'What is URL encoding?', a: 'URL encoding (percent encoding) converts characters that are not allowed in URLs into a % followed by two hexadecimal digits.' },
    ],
  },
  {
    slug: 'jwt-decoder',
    category: 'developer',
    name: 'JWT Decoder',
    tagline: 'Decode and inspect JWT tokens instantly',
    description: 'Decode JSON Web Tokens (JWT) to inspect their header, payload, and signature. Debug authentication issues quickly.',
    h1: 'JWT Decoder Tool – Decode & Inspect JWTs Online',
    metaTitle: 'JWT Decoder Online – Decode JSON Web Tokens Free',
    metaDescription: 'Decode and inspect JWT tokens online. View the header, payload, and expiration of any JSON Web Token — free, no signup, works in your browser.',
    keywords: ['jwt decoder', 'decode jwt', 'json web token decoder', 'jwt inspector', 'jwt parser online'],
    icon: '🔑',
    component: 'JWTDecoder',
    relatedSlugs: ['base64-encode', 'url-encoder'],
    faq: [
      { q: 'What is a JWT?', a: 'A JSON Web Token (JWT) is a compact, URL-safe way to represent claims between two parties. It consists of a header, payload, and signature, separated by dots.' },
      { q: 'Is it safe to decode my JWT here?', a: 'Yes. All decoding is done locally in your browser using JavaScript. Your token is never sent to any server.' },
    ],
  },
  {
    slug: 'regex-tester',
    category: 'developer',
    name: 'Regex Tester',
    tagline: 'Test and debug regular expressions live',
    description: 'Test regular expressions with live match highlighting. Supports flags, capture groups, and detailed match information.',
    h1: 'Regex Tester & Debugger (Free Online)',
    metaTitle: 'Regex Tester Online – Test Regular Expressions Free',
    metaDescription: 'Test and debug regular expressions online with live match highlighting. Supports all JavaScript regex flags — free, no signup required.',
    keywords: ['regex tester', 'regular expression tester', 'test regex online', 'regex debugger', 'regex checker'],
    icon: '🔍',
    component: 'RegexTester',
    relatedSlugs: ['json-formatter', 'url-encoder'],
    faq: [
      { q: 'What regex flavor does this support?', a: 'This tester uses JavaScript (ECMAScript) regular expression syntax, which supports flags: g, i, m, s, u, y.' },
    ],
  },

  // ── TEXT ───────────────────────────────────────────────────────────────────
  {
    slug: 'word-counter',
    category: 'text',
    name: 'Word Counter',
    tagline: 'Count words, characters, sentences & reading time',
    description: 'Free online word counter that counts words, characters, sentences, paragraphs, and estimates reading time. Perfect for essays, blog posts, and social media.',
    h1: 'Word Counter Tool – Count Words & Characters Free',
    metaTitle: 'Word Counter Online – Count Words, Characters & Reading Time',
    metaDescription: 'Count words, characters, sentences, and paragraphs instantly. Get reading time estimates for your text — free online word counter, no signup.',
    keywords: ['word counter', 'character counter', 'word count online', 'count words free', 'reading time calculator'],
    icon: '📝',
    component: 'WordCounter',
    popular: true,
    relatedSlugs: ['case-converter', 'remove-line-breaks', 'text-sorter'],
    faq: [
      { q: 'How is reading time calculated?', a: 'Reading time is calculated based on an average reading speed of 200 words per minute, which is typical for most adults.' },
      { q: 'Does it count spaces as characters?', a: 'We show both: characters with spaces and characters without spaces. Toggle between them using the display options.' },
      { q: 'What\'s the maximum text length?', a: 'There is no limit. The counter processes text entirely in your browser with no server upload.' },
    ],
  },
  {
    slug: 'case-converter',
    category: 'text',
    name: 'Case Converter',
    tagline: 'Convert text to UPPER, lower, Title, or camelCase',
    description: 'Convert text between uppercase, lowercase, title case, sentence case, camelCase, PascalCase, snake_case, and kebab-case.',
    h1: 'Case Converter Tool – Convert Text Case Online Free',
    metaTitle: 'Case Converter Online – UPPER, lower, Title, camelCase & More',
    metaDescription: 'Convert text to uppercase, lowercase, title case, camelCase, snake_case and more. Free online case converter — instant, no signup required.',
    keywords: ['case converter', 'text case converter', 'uppercase converter', 'lowercase converter', 'camelcase converter'],
    icon: 'Aa',
    component: 'CaseConverter',
    relatedSlugs: ['word-counter', 'text-sorter'],
    faq: [
      { q: 'What cases are supported?', a: 'UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, and CONSTANT_CASE.' },
    ],
  },
  {
    slug: 'remove-line-breaks',
    category: 'text',
    name: 'Remove Line Breaks',
    tagline: 'Strip newlines and format paragraphs cleanly',
    description: 'Remove unwanted line breaks from text, PDFs, or emails. Join lines into paragraphs or a single line instantly.',
    h1: 'Remove Line Breaks from Text (Free Online Tool)',
    metaTitle: 'Remove Line Breaks Online – Strip Newlines From Text Free',
    metaDescription: 'Remove unwanted line breaks from text instantly. Clean up copied PDF text, emails, or documents — free, online, no signup required.',
    keywords: ['remove line breaks', 'strip newlines', 'remove newlines online', 'join lines tool'],
    icon: '↩',
    component: 'RemoveLineBreaks',
    relatedSlugs: ['word-counter', 'text-sorter', 'duplicate-line-remover'],
    faq: [
      { q: 'Why does copied PDF text have extra line breaks?', a: 'PDFs store text with hard line breaks at the end of each line. Our tool joins them back into flowing paragraphs.' },
    ],
  },
  {
    slug: 'text-sorter',
    category: 'text',
    name: 'Text Sorter',
    tagline: 'Sort lines alphabetically, numerically, or randomly',
    description: 'Sort lines of text alphabetically (A-Z or Z-A), by length, numerically, or randomly. Remove duplicates while sorting.',
    h1: 'Text Sorter – Sort Lines Alphabetically Online Free',
    metaTitle: 'Text Sorter Online – Sort Lines Alphabetically or Numerically',
    metaDescription: 'Sort lines of text alphabetically, numerically, by length, or randomly. Remove duplicates while sorting — free online tool, no signup.',
    keywords: ['text sorter', 'sort lines alphabetically', 'sort text online', 'alphabetize list online'],
    icon: '🔤',
    component: 'TextSorter',
    relatedSlugs: ['duplicate-line-remover', 'word-counter'],
    faq: [],
  },
  {
    slug: 'duplicate-line-remover',
    category: 'text',
    name: 'Duplicate Line Remover',
    tagline: 'Remove duplicate lines from any text instantly',
    description: 'Find and remove duplicate lines from text lists, code, CSV data, or any content. Case-sensitive or insensitive matching.',
    h1: 'Remove Duplicate Lines from Text (Free Online)',
    metaTitle: 'Duplicate Line Remover Online – Remove Duplicate Lines Free',
    metaDescription: 'Remove duplicate lines from text instantly. Case-sensitive or insensitive matching — free online duplicate remover, no signup required.',
    keywords: ['duplicate line remover', 'remove duplicate lines', 'deduplicate text', 'remove duplicates online'],
    icon: '🗑️',
    component: 'DuplicateLineRemover',
    relatedSlugs: ['text-sorter', 'remove-line-breaks'],
    faq: [],
  },

  // ── SEO ────────────────────────────────────────────────────────────────────
  {
    slug: 'meta-tag-generator',
    category: 'seo',
    name: 'Meta Tag Generator',
    tagline: 'Generate SEO meta tags for any webpage',
    description: 'Generate complete HTML meta tags including title, description, Open Graph, Twitter Cards, and robots directives. Copy and paste ready.',
    h1: 'Meta Tag Generator – Free SEO Meta Tags Tool',
    metaTitle: 'Meta Tag Generator Online – Free SEO Meta Tags Generator',
    metaDescription: 'Generate SEO meta tags, Open Graph tags, and Twitter Cards for your website. Copy-paste ready HTML — free online meta tag generator.',
    keywords: ['meta tag generator', 'seo meta tags', 'open graph generator', 'twitter card generator', 'html meta tags'],
    icon: '🏷️',
    component: 'MetaTagGenerator',
    popular: true,
    relatedSlugs: ['slug-generator', 'robots-txt-generator', 'keyword-density'],
    faq: [
      { q: 'What meta tags are most important for SEO?', a: 'The title tag and meta description are most critical. Open Graph tags (og:title, og:description, og:image) are essential for social sharing.' },
      { q: 'How long should a meta description be?', a: 'Google typically displays 155–160 characters. Keep your description under 160 characters to avoid truncation in search results.' },
    ],
  },
  {
    slug: 'keyword-density',
    category: 'seo',
    name: 'Keyword Density Checker',
    tagline: 'Analyze keyword frequency in your content',
    description: 'Check keyword density and frequency in any text. Find over-used or under-used keywords to optimize your content for SEO.',
    h1: 'Keyword Density Checker (Free SEO Tool)',
    metaTitle: 'Keyword Density Checker Online – Free SEO Analysis Tool',
    metaDescription: 'Analyze keyword frequency and density in your content. Find the most common words and phrases — free keyword density checker, no signup.',
    keywords: ['keyword density checker', 'keyword frequency', 'keyword analyzer', 'seo keyword tool', 'content analysis'],
    icon: '📊',
    component: 'KeywordDensity',
    relatedSlugs: ['meta-tag-generator', 'word-counter'],
    faq: [],
  },
  {
    slug: 'slug-generator',
    category: 'seo',
    name: 'Slug Generator',
    tagline: 'Convert titles to SEO-friendly URL slugs',
    description: 'Generate clean, SEO-friendly URL slugs from article titles. Handles special characters, accents, and multiple languages.',
    h1: 'URL Slug Generator – Create SEO-Friendly Slugs Free',
    metaTitle: 'Slug Generator Online – Create SEO-Friendly URL Slugs Free',
    metaDescription: 'Convert article titles and headings to SEO-friendly URL slugs. Handles special characters and accents — free slug generator, no signup.',
    keywords: ['slug generator', 'url slug generator', 'seo slug', 'permalink generator', 'url friendly slug'],
    icon: '🐌',
    component: 'SlugGenerator',
    relatedSlugs: ['meta-tag-generator', 'url-encoder'],
    faq: [],
  },
  {
    slug: 'robots-txt-generator',
    category: 'seo',
    name: 'Robots.txt Generator',
    tagline: 'Generate a robots.txt file for your website',
    description: 'Create a valid robots.txt file to control search engine crawling. Supports multiple user agents, allow/disallow rules, and sitemaps.',
    h1: 'Robots.txt Generator (Free Online SEO Tool)',
    metaTitle: 'Robots.txt Generator Online – Create robots.txt Free',
    metaDescription: 'Generate a robots.txt file for your website in seconds. Control which pages search engines can crawl — free robots.txt generator, no signup.',
    keywords: ['robots txt generator', 'create robots.txt', 'robots.txt file generator', 'seo robots txt'],
    icon: '🤖',
    component: 'RobotsTxtGenerator',
    relatedSlugs: ['meta-tag-generator', 'slug-generator'],
    faq: [
      { q: 'What is robots.txt?', a: 'Robots.txt is a text file at the root of your domain that tells search engine crawlers which pages or files they can or cannot request from your site.' },
    ],
  },

  // ── IMAGE ──────────────────────────────────────────────────────────────────
  {
    slug: 'image-compressor',
    category: 'image',
    name: 'Image Compressor',
    tagline: 'Compress images without visible quality loss',
    description: 'Free online image compressor. Reduce JPEG, PNG, and WebP file sizes by up to 80% without noticeable quality loss. Batch compress up to 20 images.',
    h1: 'Image Compressor – Compress Images Online Free',
    metaTitle: 'Image Compressor Online – Compress JPEG, PNG & WebP Free',
    metaDescription: 'Compress JPEG, PNG, and WebP images online without losing quality. Reduce file size by up to 80% — free image compressor, no signup required.',
    keywords: ['image compressor', 'compress image online', 'reduce image size', 'jpeg compressor', 'png compressor'],
    icon: '🗜️',
    component: 'ImageCompressor',
    popular: true,
    relatedSlugs: ['jpg-to-png', 'png-to-webp', 'image-resizer'],
    faq: [
      { q: 'How much can images be compressed?', a: 'JPEG images can often be reduced by 40-80% with minimal quality loss. PNG files benefit from lossless compression, typically 10-30% reduction.' },
      { q: 'Are my images uploaded to a server?', a: 'No. All compression happens locally in your browser using the Canvas API and browser-image-compression library. Your images never leave your device.' },
      { q: 'What formats are supported?', a: 'JPEG, JPG, PNG, and WebP are fully supported.' },
      { q: 'Can I compress multiple images at once?', a: 'Yes, drag and drop up to 20 images at once for batch compression.' },
    ],
  },
  {
    slug: 'jpg-to-png',
    category: 'image',
    name: 'JPG to PNG Converter',
    tagline: 'Convert JPEG images to PNG with transparency support',
    description: 'Convert JPG/JPEG images to PNG format online. Preserve quality and add transparency support. Fast, free, and no signup required.',
    h1: 'JPG to PNG Converter (Free Online)',
    metaTitle: 'JPG to PNG Converter Online – Convert JPEG to PNG Free',
    metaDescription: 'Convert JPG images to PNG format online. Free, fast, and no quality loss — JPG to PNG converter with transparency support, no signup.',
    keywords: ['jpg to png', 'jpeg to png converter', 'convert jpg to png online', 'jpg png converter'],
    icon: '🖼️',
    component: 'ImageConverter',
    relatedSlugs: ['png-to-webp', 'image-compressor'],
    faq: [],
  },
  {
    slug: 'png-to-webp',
    category: 'image',
    name: 'PNG to WebP Converter',
    tagline: 'Convert PNG images to modern WebP format',
    description: 'Convert PNG images to WebP format for smaller file sizes and faster websites. WebP offers 25-34% smaller files than PNG.',
    h1: 'PNG to WebP Converter (Free Online)',
    metaTitle: 'PNG to WebP Converter Online – Convert PNG to WebP Free',
    metaDescription: 'Convert PNG images to WebP format online. WebP files are 25-34% smaller than PNG — free PNG to WebP converter, no signup required.',
    keywords: ['png to webp', 'convert png to webp', 'webp converter', 'png webp online'],
    icon: '✨',
    component: 'ImageConverter',
    relatedSlugs: ['jpg-to-png', 'image-compressor'],
    faq: [],
  },
  {
    slug: 'image-resizer',
    category: 'image',
    name: 'Image Resizer',
    tagline: 'Resize images to exact dimensions online',
    description: 'Resize images to any dimension online. Maintain aspect ratio, crop, or stretch. Supports JPEG, PNG, and WebP.',
    h1: 'Image Resizer – Resize Images Online Free',
    metaTitle: 'Image Resizer Online – Resize Images to Any Size Free',
    metaDescription: 'Resize images to any dimension online. Maintain aspect ratio or set custom dimensions — free image resizer, no signup required.',
    keywords: ['image resizer', 'resize image online', 'change image size', 'image dimensions tool'],
    icon: '📐',
    component: 'ImageResizer',
    relatedSlugs: ['image-compressor', 'jpg-to-png'],
    faq: [],
  },

  // ── PDF ────────────────────────────────────────────────────────────────────
  {
    slug: 'pdf-merge',
    category: 'pdf',
    name: 'PDF Merge',
    tagline: 'Combine multiple PDF files into one document',
    description: 'Merge multiple PDF files into a single document online. Drag to reorder pages, set custom order, and download instantly. 100% free.',
    h1: 'PDF Merge Tool – Combine PDF Files Online Free',
    metaTitle: 'PDF Merge Online – Combine Multiple PDFs Into One Free',
    metaDescription: 'Merge multiple PDF files into one document online. Drag to reorder, combine, and download — free PDF merger tool, no signup required.',
    keywords: ['pdf merge', 'merge pdf online', 'combine pdf files', 'pdf combiner', 'join pdf files'],
    icon: '📎',
    component: 'PDFMerge',
    popular: true,
    relatedSlugs: ['pdf-split', 'pdf-compressor', 'pdf-to-word'],
    faq: [
      { q: 'How many PDFs can I merge at once?', a: 'You can merge up to 20 PDF files at once. For larger batches, merge in groups and then combine the results.' },
      { q: 'Is PDF merging secure?', a: 'Yes. PDF processing is done entirely in your browser using pdf-lib. Your files are never uploaded to any server.' },
      { q: 'Can I reorder pages before merging?', a: 'Yes. Drag and drop the files to set the order before merging.' },
    ],
  },
  {
    slug: 'pdf-split',
    category: 'pdf',
    name: 'PDF Split',
    tagline: 'Split a PDF into separate pages or ranges',
    description: 'Split a PDF file into individual pages or custom page ranges. Extract specific pages from large PDF documents.',
    h1: 'PDF Split Tool – Split PDF Pages Online Free',
    metaTitle: 'PDF Split Online – Extract Pages from PDF Free',
    metaDescription: 'Split a PDF into individual pages or custom ranges online. Extract pages from PDF documents — free PDF splitter, no signup required.',
    keywords: ['pdf split', 'split pdf online', 'extract pdf pages', 'pdf page extractor', 'split pdf free'],
    icon: '✂️',
    component: 'PDFSplit',
    relatedSlugs: ['pdf-merge', 'pdf-compressor'],
    faq: [],
  },
  {
    slug: 'pdf-compressor',
    category: 'pdf',
    name: 'PDF Compressor',
    tagline: 'Reduce PDF file size without losing quality',
    description: 'Compress PDF files to reduce their size for email or upload. Maintains readable quality for most documents.',
    h1: 'PDF Compressor – Reduce PDF File Size Online Free',
    metaTitle: 'PDF Compressor Online – Compress PDF Files Free',
    metaDescription: 'Compress and reduce PDF file size online. Ideal for email attachments and uploads — free PDF compressor, no signup required.',
    keywords: ['pdf compressor', 'compress pdf online', 'reduce pdf size', 'pdf file size reducer'],
    icon: '📉',
    component: 'PDFCompressor',
    relatedSlugs: ['pdf-merge', 'pdf-split'],
    faq: [],
  },
  {
    slug: 'pdf-to-word',
    category: 'pdf',
    name: 'PDF to Word',
    tagline: 'Convert PDF documents to editable Word files',
    description: 'Convert PDF files to editable Word documents (.docx). Preserves formatting and text for further editing.',
    h1: 'PDF to Word Converter (Free Online)',
    metaTitle: 'PDF to Word Converter Online – Convert PDF to DOCX Free',
    metaDescription: 'Convert PDF files to editable Word documents online. Preserve formatting and extract text — free PDF to Word converter, no signup.',
    keywords: ['pdf to word', 'pdf to docx', 'convert pdf to word online', 'pdf word converter free'],
    icon: '📄',
    component: 'PDFToWord',
    relatedSlugs: ['pdf-merge', 'pdf-split', 'pdf-compressor'],
    faq: [
      { q: 'How accurate is the PDF to Word conversion?', a: 'Accuracy depends on the PDF type. Text-based PDFs convert very well. Scanned PDFs require OCR and may have some formatting differences.' },
    ],
  },

  // ── CONVERTER ──────────────────────────────────────────────────────────────
  {
    slug: 'cm-to-inch',
    category: 'converter',
    name: 'cm to inch Converter',
    tagline: 'Convert centimeters to inches instantly',
    description: 'Convert centimeters to inches with a simple, accurate calculator. Includes a reference table for common values.',
    h1: 'cm to inch Converter (Free Online Calculator)',
    metaTitle: 'cm to inches Converter – Convert Centimeters to Inches Online',
    metaDescription: 'Convert centimeters to inches online instantly. Accurate cm to inch calculator with formula explanation — free, no signup required.',
    keywords: ['cm to inches', 'centimeter to inch', 'cm inch converter', 'convert cm to inches'],
    icon: '📏',
    component: 'UnitConverter',
    relatedSlugs: ['kg-to-lbs', 'celsius-to-fahrenheit'],
    faq: [
      { q: 'How many inches is 1 cm?', a: '1 centimeter equals 0.393701 inches. Conversely, 1 inch equals 2.54 centimeters.' },
    ],
  },
  {
    slug: 'kg-to-lbs',
    category: 'converter',
    name: 'kg to lbs Converter',
    tagline: 'Convert kilograms to pounds instantly',
    description: 'Convert kilograms to pounds accurately. Includes formula, reference table, and reverse conversion.',
    h1: 'kg to lbs Converter (Free Online Calculator)',
    metaTitle: 'kg to lbs Converter – Convert Kilograms to Pounds Online Free',
    metaDescription: 'Convert kilograms to pounds online instantly. Accurate kg to lbs calculator with formula — free, no signup required.',
    keywords: ['kg to lbs', 'kilograms to pounds', 'kg lbs converter', 'convert kg to pounds'],
    icon: '⚖️',
    component: 'UnitConverter',
    relatedSlugs: ['cm-to-inch', 'celsius-to-fahrenheit'],
    faq: [],
  },
  {
    slug: 'celsius-to-fahrenheit',
    category: 'converter',
    name: 'Celsius to Fahrenheit',
    tagline: 'Convert temperature between °C and °F',
    description: 'Convert Celsius to Fahrenheit and Fahrenheit to Celsius instantly. Includes the formula and a reference chart.',
    h1: 'Celsius to Fahrenheit Converter (Free Online)',
    metaTitle: 'Celsius to Fahrenheit Converter Online – °C to °F Free',
    metaDescription: 'Convert Celsius to Fahrenheit online instantly. Accurate temperature converter with formula and chart — free, no signup required.',
    keywords: ['celsius to fahrenheit', 'celsius fahrenheit converter', 'c to f converter', 'temperature converter online'],
    icon: '🌡️',
    component: 'UnitConverter',
    relatedSlugs: ['cm-to-inch', 'kg-to-lbs'],
    faq: [
      { q: 'What is the formula for Celsius to Fahrenheit?', a: '°F = (°C × 9/5) + 32. For example, 100°C = (100 × 9/5) + 32 = 212°F.' },
    ],
  },
  {
    slug: 'timestamp-converter',
    category: 'converter',
    name: 'Timestamp Converter',
    tagline: 'Convert Unix timestamps to human-readable dates',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Supports seconds and milliseconds, multiple timezones, ISO 8601, and relative time.',
    h1: 'Unix Timestamp Converter (Free & Online)',
    metaTitle: 'Unix Timestamp Converter Online – Free Epoch Time Converter',
    metaDescription: 'Convert Unix timestamps to readable dates and back online. Supports seconds, milliseconds, timezones, ISO 8601 — free timestamp converter, no signup.',
    keywords: ['unix timestamp', 'epoch converter', 'timestamp to date', 'date to timestamp', 'unix time converter', 'epoch time'],
    icon: '⏱️',
    component: 'TimestampConverter',
    new: true,
    relatedSlugs: ['cm-to-inch', 'kg-to-lbs'],
    faq: [
      { q: 'What is a Unix timestamp?', a: 'A Unix timestamp is the number of seconds elapsed since January 1, 1970 at 00:00:00 UTC (the Unix epoch). It is used universally in programming to represent a specific moment in time.' },
      { q: 'What is the difference between seconds and milliseconds timestamps?', a: 'Unix timestamps in seconds are 10 digits (e.g. 1705276800). Millisecond timestamps are 13 digits (e.g. 1705276800000). This converter detects both automatically.' },
    ],
  },

  // ── DEVELOPER (utilities) ──────────────────────────────────────────────
  {
    slug: 'password-generator',
    category: 'developer',
    name: 'Password Generator',
    tagline: 'Generate strong, random passwords instantly',
    description: 'Free online password generator. Create secure random passwords with custom length, character sets, and bulk generation. Strength indicator included.',
    h1: 'Password Generator – Create Strong Passwords Free',
    metaTitle: 'Password Generator Online – Generate Strong Random Passwords Free',
    metaDescription: 'Generate strong, random passwords instantly. Customize length, character types, and generate up to 20 passwords at once — free, no signup, works in your browser.',
    keywords: ['password generator', 'random password', 'strong password generator', 'secure password', 'generate password online'],
    icon: '🔐',
    component: 'PasswordGenerator',
    popular: true,
    new: true,
    relatedSlugs: ['uuid-generator', 'base64-encode', 'jwt-decoder'],
    faq: [
      { q: 'How long should a password be?', a: 'At least 16 characters for most accounts. For high-value accounts (email, banking), use 20+ characters with all character types.' },
      { q: 'Are generated passwords stored?', a: 'No. Passwords are generated entirely in your browser using the Web Crypto API. Nothing is sent to any server.' },
      { q: 'Should I use all character types?', a: 'Yes. Using uppercase, lowercase, digits, and symbols maximizes entropy and makes passwords exponentially harder to crack.' },
    ],
  },
  {
    slug: 'uuid-generator',
    category: 'developer',
    name: 'UUID Generator',
    tagline: 'Generate RFC 4122 compliant UUID v4 values',
    description: 'Free online UUID generator. Create one or hundreds of RFC 4122 UUID v4 values instantly. Options for uppercase, no-hyphens format. Copy all at once.',
    h1: 'UUID Generator – Generate UUID v4 Online Free',
    metaTitle: 'UUID Generator Online – Generate UUID v4 Free',
    metaDescription: 'Generate RFC 4122 UUID v4 values online. Create up to 100 UUIDs at once with uppercase and hyphen options — free UUID generator, no signup.',
    keywords: ['uuid generator', 'uuid v4', 'generate uuid', 'random uuid', 'guid generator', 'unique id generator'],
    icon: '🆔',
    component: 'UUIDGenerator',
    new: true,
    relatedSlugs: ['password-generator', 'base64-encode'],
    faq: [
      { q: 'What is UUID v4?', a: 'UUID v4 uses 122 bits of cryptographically random data. The collision probability is so low (1 in 5.3×10³⁶) that duplicates are practically impossible.' },
      { q: 'What is the difference between UUID and GUID?', a: 'GUID (Globally Unique Identifier) is Microsoft\'s term for UUID. They are the same format and fully compatible.' },
    ],
  },
  {
    slug: 'lorem-ipsum-generator',
    category: 'text',
    name: 'Lorem Ipsum Generator',
    tagline: 'Generate placeholder text for mockups and wireframes',
    description: 'Free online Lorem Ipsum generator. Generate paragraphs, sentences, or words of placeholder text for mockups, wireframes, and designs.',
    h1: 'Lorem Ipsum Generator – Free Placeholder Text',
    metaTitle: 'Lorem Ipsum Generator Online – Free Placeholder Text',
    metaDescription: 'Generate Lorem Ipsum placeholder text online. Choose paragraphs, sentences, or words — free Lorem Ipsum generator, no signup required.',
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator', 'lorem ipsum online', 'filler text'],
    icon: '📄',
    component: 'LoremIpsumGenerator',
    new: true,
    relatedSlugs: ['word-counter', 'case-converter'],
    faq: [
      { q: 'What is Lorem Ipsum?', a: "Lorem Ipsum is placeholder text used in graphic design and publishing. It's derived from a scrambled passage of Cicero's 45 BC work \"de Finibus Bonorum et Malorum\"." },
      { q: 'Why use Lorem Ipsum?', a: "Lorem Ipsum looks like readable English but has no meaning, so reviewers focus on the design layout rather than the text content. It's the standard placeholder for UI mockups and print layouts." },
    ],
  },
  {
    slug: 'number-base-converter',
    category: 'converter',
    name: 'Number Base Converter',
    tagline: 'Convert between binary, octal, decimal & hex',
    description: 'Free online number base converter. Convert numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16) instantly.',
    h1: 'Number Base Converter – Binary, Octal, Decimal, Hex',
    metaTitle: 'Number Base Converter Online – Binary, Octal, Decimal, Hex Free',
    metaDescription: 'Convert numbers between binary, octal, decimal, and hexadecimal online. Instant number base converter with reference table — free, no signup.',
    keywords: ['number base converter', 'binary to decimal', 'hex to decimal', 'decimal to binary', 'octal converter', 'base converter'],
    icon: '🔢',
    component: 'NumberBaseConverter',
    new: true,
    relatedSlugs: ['timestamp-converter', 'cm-to-inch'],
    faq: [
      { q: 'What is binary?', a: 'Binary is base-2 number system using only 0 and 1. Computers use binary internally because transistors have two states: on (1) and off (0).' },
      { q: 'What is hexadecimal used for?', a: 'Hexadecimal (base 16) is used in programming for memory addresses, color codes (#FF5733), bytecodes, and representing binary data compactly.' },
    ],
  },
  {
    slug: 'html-entity-encoder',
    category: 'developer',
    name: 'HTML Entity Encoder',
    tagline: 'Encode & decode HTML entities instantly',
    description: 'Free online HTML entity encoder and decoder. Convert special characters to named or numeric HTML entities and back. Essential for safe HTML output.',
    h1: 'HTML Entity Encoder & Decoder (Free Online)',
    metaTitle: 'HTML Entity Encoder Decoder Online – Free HTML Entity Tool',
    metaDescription: 'Encode and decode HTML entities online. Convert special characters to &amp;, &lt;, &gt; and numeric entities — free HTML entity encoder, no signup.',
    keywords: ['html entity encoder', 'html entity decoder', 'encode html entities', 'html special characters', 'html escape'],
    icon: '🏷️',
    component: 'HTMLEntityEncoder',
    new: true,
    relatedSlugs: ['html-formatter', 'html-viewer', 'url-encoder'],
    faq: [
      { q: 'What are HTML entities?', a: 'HTML entities are codes used to represent characters that have special meaning in HTML (like <, >, &) or characters outside the basic ASCII range. For example, &lt; represents <.' },
      { q: 'When should I encode HTML?', a: 'Always encode user-supplied content before inserting it into HTML to prevent XSS (Cross-Site Scripting) attacks. Any < > & " \' characters from users must be escaped.' },
    ],
  },

  // ── DEVELOPER (additional) ──────────────────────────────────────────────
  {
    slug: 'css-minifier',
    category: 'developer',
    name: 'CSS Minifier',
    tagline: 'Minify CSS to reduce file size instantly',
    description: 'Free online CSS minifier. Remove comments, whitespace, and redundant code from CSS files to reduce file size for faster page loads.',
    h1: 'CSS Minifier – Minify CSS Online Free',
    metaTitle: 'CSS Minifier Online – Compress & Minify CSS Free',
    metaDescription: 'Minify and compress CSS online. Remove comments and whitespace to reduce file size — free CSS minifier, no signup required.',
    keywords: ['css minifier', 'minify css', 'compress css', 'css compressor', 'css minify online'],
    icon: '🎨',
    component: 'CSSMinifier',
    new: true,
    relatedSlugs: ['js-minifier', 'json-minify', 'html-formatter'],
    faq: [
      { q: 'What does CSS minification do?', a: 'CSS minification removes comments, whitespace, and unnecessary characters from your CSS code without changing how it functions. This reduces file size and improves page load time.' },
      { q: 'Is minified CSS valid CSS?', a: 'Yes. Minified CSS is 100% valid and produces identical visual output to the original. Browsers parse both identically.' },
    ],
  },
  {
    slug: 'js-minifier',
    category: 'developer',
    name: 'JS Minifier',
    tagline: 'Minify JavaScript by removing comments & whitespace',
    description: 'Free online JavaScript minifier. Remove comments and unnecessary whitespace from JS files to reduce bundle size.',
    h1: 'JavaScript Minifier – Minify JS Online Free',
    metaTitle: 'JS Minifier Online – Compress & Minify JavaScript Free',
    metaDescription: 'Minify JavaScript online. Remove comments and whitespace to reduce file size — free JS minifier tool, no signup required.',
    keywords: ['js minifier', 'javascript minifier', 'minify javascript', 'compress js', 'js compressor online'],
    icon: '📦',
    component: 'JSMinifier',
    new: true,
    relatedSlugs: ['css-minifier', 'json-minify', 'json-formatter'],
    faq: [
      { q: 'What does JS minification do?', a: 'JS minification removes comments, extra whitespace, and newlines from JavaScript code. This reduces file size, improving page load speeds without changing functionality.' },
      { q: 'Should I minify JavaScript for production?', a: 'Yes. Minification is a standard step in production builds. For advanced optimization (variable renaming, dead code elimination), use a build tool like webpack, esbuild, or Rollup.' },
    ],
  },
  {
    slug: 'color-converter',
    category: 'developer',
    name: 'Color Picker & Palette Generator',
    tagline: 'Pick a color, generate scales, and copy design-ready values',
    description: 'Free online color picker and palette generator. Create design-ready shade scales, convert between HEX, RGB, and HSL, and copy CSS-ready values instantly.',
    h1: 'Color Picker & Palette Generator Online',
    metaTitle: 'Color Picker & Palette Generator – HEX, RGB & HSL',
    metaDescription: 'Generate palettes from any color, convert HEX, RGB, and HSL, and copy CSS-ready values instantly. Free, fast, and browser-based.',
    keywords: ['color picker', 'palette generator', 'hex to rgb', 'rgb to hex', 'hex to hsl', 'design palette'],
    icon: '🎨',
    component: 'ColorConverter',
    new: true,
    popular: true,
    relatedSlugs: ['css-minifier', 'meta-tag-generator'],
    faq: [
      { q: 'What is HEX color?', a: 'HEX (hexadecimal) color is a 6-digit code that represents a color using values 00-FF for red, green, and blue channels. Example: #0ea5e9 is a sky blue.' },
      { q: 'What is HSL color?', a: 'HSL stands for Hue, Saturation, and Lightness. It is a more human-intuitive way to describe colors — hue (0-360°), saturation (0-100%), and lightness (0-100%).' },
    ],
  },
  {
    slug: 'background-remover',
    category: 'image',
    name: 'Background Remover',
    tagline: 'Remove flat backdrops and export transparent PNG files',
    description: 'Free online background remover for clean product shots and UI assets. Upload an image, tune the threshold, and export a transparent PNG directly in the browser.',
    h1: 'Background Remover Tool (Free & Online)',
    metaTitle: 'Background Remover Online – Transparent PNG Export',
    metaDescription: 'Remove simple image backgrounds online, fine-tune threshold controls, and download transparent PNG files instantly. Free and browser-based.',
    keywords: ['background remover', 'transparent png', 'remove image background', 'product photo cleaner'],
    icon: '✂️',
    component: 'BackgroundRemover',
    new: true,
    popular: true,
    relatedSlugs: ['image-enhancer', 'image-resizer', 'png-to-webp'],
    faq: [
      { q: 'Does this tool use an API?', a: 'This version runs in your browser and is optimized for simple flat or studio-style backdrops. It is designed as a fast built-in workspace tool.' },
      { q: 'What file format should I export?', a: 'PNG is the best choice when you need transparency, especially for product cards, mockups, or UI assets.' },
    ],
  },
  {
    slug: 'image-enhancer',
    category: 'image',
    name: 'Image Cleaner / Enhancer',
    tagline: 'Improve clarity, contrast, saturation, and exposure in one pass',
    description: 'Free online image cleaner and enhancer. Adjust brightness, contrast, saturation, and cleanup intensity to prep screenshots, mockups, and marketing visuals.',
    h1: 'Image Cleaner & Enhancer Tool (Free Online)',
    metaTitle: 'Image Cleaner & Enhancer Online – Improve Photos Fast',
    metaDescription: 'Clean up and enhance images in your browser. Tune exposure, contrast, saturation, and clarity, then export the improved image instantly.',
    keywords: ['image enhancer', 'image cleaner', 'photo enhancement', 'improve screenshot quality'],
    icon: '✨',
    component: 'ImageEnhancer',
    new: true,
    relatedSlugs: ['background-remover', 'image-compressor', 'image-resizer'],
    faq: [
      { q: 'What kind of improvements can I make?', a: 'You can quickly improve screenshots and product visuals with exposure, contrast, saturation, warmth, and cleanup adjustments.' },
      { q: 'Is the original file uploaded anywhere?', a: 'No. Image processing happens locally in the browser, so the file stays on the device.' },
    ],
  },
  {
    slug: 'markdown-previewer',
    category: 'developer',
    name: 'Markdown Previewer',
    tagline: 'Write Markdown on the left and preview it live on the right',
    description: 'Free online Markdown previewer with live rendering, copy actions, and sample content. Great for README files, docs, release notes, and internal guides.',
    h1: 'Markdown Previewer Tool (Free Online)',
    metaTitle: 'Markdown Previewer Online – Live README Preview',
    metaDescription: 'Preview Markdown live in your browser. Ideal for README files, documentation, and changelogs. Free, fast, and no signup required.',
    keywords: ['markdown previewer', 'markdown editor', 'readme preview', 'markdown live preview'],
    icon: '📝',
    component: 'MarkdownPreviewer',
    new: true,
    popular: true,
    relatedSlugs: ['html-viewer', 'code-formatter', 'remove-line-breaks'],
    faq: [
      { q: 'What is Markdown used for?', a: 'Markdown is commonly used for README files, technical docs, changelogs, wikis, and note-taking because it is easy to write and easy to render.' },
    ],
  },
  {
    slug: 'code-formatter',
    category: 'developer',
    name: 'Code Formatter',
    tagline: 'Format HTML, CSS, and JavaScript from one workspace',
    description: 'Free online code formatter for HTML, CSS, and JavaScript. Switch languages, format messy snippets, and copy clean output instantly.',
    h1: 'Code Formatter – HTML, CSS & JavaScript',
    metaTitle: 'Code Formatter Online – HTML, CSS & JS Beautifier',
    metaDescription: 'Format HTML, CSS, and JavaScript online from a single browser-based workspace. Clean code fast with copy-ready output.',
    keywords: ['code formatter', 'html formatter', 'css formatter', 'javascript formatter', 'beautify code'],
    icon: '🧩',
    component: 'CodeFormatter',
    new: true,
    popular: true,
    relatedSlugs: ['html-formatter', 'css-minifier', 'js-minifier'],
    faq: [
      { q: 'Which languages are supported?', a: 'The formatter supports HTML, CSS, and JavaScript in one interface so you can clean up front-end snippets quickly.' },
    ],
  },
  {
    slug: 'data-format-converter',
    category: 'developer',
    name: 'Data Format Converter',
    tagline: 'Convert JSON, YAML, XML, and CSV in one browser workspace',
    description: 'Free online data format converter for JSON, YAML, XML, and CSV. Transform payloads, config files, and exports instantly without leaving the browser.',
    h1: 'Data Format Converter – JSON, YAML, XML & CSV',
    metaTitle: 'Data Format Converter Online – JSON, YAML, XML & CSV',
    metaDescription: 'Convert JSON, YAML, XML, and CSV instantly in your browser. Great for config files, API payloads, and tabular exports.',
    keywords: ['json yaml converter', 'xml to json', 'csv converter', 'data format converter', 'yaml xml csv'],
    icon: '⇄',
    component: 'DataFormatConverter',
    new: true,
    popular: true,
    relatedSlugs: ['json-formatter', 'query-params-parser', 'json-diff'],
    faq: [
      { q: 'Which formats can I convert between?', a: 'This tool supports JSON, YAML, XML, and CSV in one browser-based workspace.' },
    ],
  },
  {
    slug: 'json-diff',
    category: 'developer',
    name: 'JSON Diff Checker',
    tagline: 'Compare two JSON payloads after formatting normalization',
    description: 'Free online JSON diff checker. Compare two JSON documents side by side after normalizing formatting, then quickly spot added, removed, or unchanged lines.',
    h1: 'JSON Diff Checker (Free Online)',
    metaTitle: 'JSON Diff Checker Online – Compare JSON Payloads',
    metaDescription: 'Compare two JSON payloads online, normalize formatting, and review line-level differences instantly. Free and browser-based.',
    keywords: ['json diff', 'compare json', 'json compare online', 'json diff checker'],
    icon: 'Δ',
    component: 'DiffChecker',
    new: true,
    popular: true,
    relatedSlugs: ['json-formatter', 'text-diff', 'data-format-converter'],
    faq: [
      { q: 'Does the JSON diff normalize formatting first?', a: 'Yes. The tool parses and reprints JSON before comparing so whitespace differences do not create noisy output.' },
    ],
  },
  {
    slug: 'text-diff',
    category: 'text',
    name: 'Text Diff Checker',
    tagline: 'Compare two text blocks line by line in the browser',
    description: 'Free online text diff checker. Paste two text blocks and compare them line by line to highlight additions, removals, and unchanged content.',
    h1: 'Text Diff Checker (Free Online)',
    metaTitle: 'Text Diff Checker Online – Compare Text Side by Side',
    metaDescription: 'Compare two text blocks online and review line-by-line differences instantly. Great for notes, content edits, and plain text changes.',
    keywords: ['text diff', 'compare text online', 'line diff checker', 'plain text compare'],
    icon: '≠',
    component: 'DiffChecker',
    new: true,
    relatedSlugs: ['json-diff', 'remove-line-breaks', 'text-sorter'],
    faq: [
      { q: 'How does the text diff work?', a: 'It compares your left and right inputs line by line so small edits are easy to spot in plain text.' },
    ],
  },
  {
    slug: 'hash-generator',
    category: 'developer',
    name: 'Hash Generator',
    tagline: 'Generate SHA hashes in the browser for quick verification',
    description: 'Free online hash generator for SHA-1, SHA-256, SHA-384, and SHA-512. Generate browser-side hashes for integrity checks and quick verification workflows.',
    h1: 'Hash Generator – SHA-1, SHA-256, SHA-384 & SHA-512',
    metaTitle: 'Hash Generator Online – SHA Hash Tool Free',
    metaDescription: 'Generate SHA hashes online in the browser. Supports SHA-1, SHA-256, SHA-384, and SHA-512 for quick verification workflows.',
    keywords: ['hash generator', 'sha256 generator', 'sha512 hash', 'sha hash online'],
    icon: '#',
    component: 'HashToolkit',
    new: true,
    popular: true,
    relatedSlugs: ['hmac-generator', 'base64-encode', 'jwt-decoder'],
    faq: [
      { q: 'Is hashing the same as encryption?', a: 'No. Hashing is one-way and is commonly used for checksums, verification, and fingerprints rather than reversible encryption.' },
    ],
  },
  {
    slug: 'hmac-generator',
    category: 'developer',
    name: 'HMAC Generator',
    tagline: 'Generate keyed HMAC signatures for API authentication flows',
    description: 'Free online HMAC generator. Create SHA-based HMAC signatures in the browser for request signing, API authentication, and secure message verification.',
    h1: 'HMAC Generator for API Signing',
    metaTitle: 'HMAC Generator Online – Browser-Based API Signing Tool',
    metaDescription: 'Generate keyed HMAC signatures online for API authentication and request signing. Free, fast, and browser-based.',
    keywords: ['hmac generator', 'api signing', 'request signature generator', 'hmac sha256'],
    icon: '🔏',
    component: 'HashToolkit',
    new: true,
    relatedSlugs: ['hash-generator', 'curl-fetch-converter', 'query-params-parser'],
    faq: [
      { q: 'What is HMAC used for?', a: 'HMAC combines a secret key and message to create a signature that can be used to verify authenticity and integrity in API workflows.' },
    ],
  },
  {
    slug: 'curl-fetch-converter',
    category: 'developer',
    name: 'cURL ↔ Fetch Converter',
    tagline: 'Convert API request snippets between cURL and fetch',
    description: 'Free online cURL and fetch converter. Turn terminal-ready API calls into browser fetch snippets or reverse them for docs, debugging, and handoff workflows.',
    h1: 'cURL ↔ Fetch Converter Tool',
    metaTitle: 'cURL to Fetch Converter Online – Fetch to cURL Too',
    metaDescription: 'Convert cURL commands to fetch requests and fetch snippets back to cURL. Free online tool for API docs and debugging workflows.',
    keywords: ['curl to fetch', 'fetch to curl', 'api snippet converter', 'curl fetch converter'],
    icon: '⇆',
    component: 'CurlFetchConverter',
    new: true,
    popular: true,
    relatedSlugs: ['query-params-parser', 'hmac-generator', 'json-formatter'],
    faq: [
      { q: 'Why convert between cURL and fetch?', a: 'Teams often document APIs in cURL but implement them in JavaScript, so converting quickly reduces copy-paste friction.' },
    ],
  },
  {
    slug: 'query-params-parser',
    category: 'developer',
    name: 'Query Params Parser',
    tagline: 'Parse query strings into JSON and build them back again',
    description: 'Free online query params parser and builder. Inspect URL search parameters as JSON, generate query strings from JSON, and copy clean outputs instantly.',
    h1: 'Query Params Parser & JSON Builder',
    metaTitle: 'Query Params Parser Online – URL Search Params to JSON',
    metaDescription: 'Parse URL query strings into JSON and generate query strings from JSON in one browser-based tool. Fast, free, and developer-friendly.',
    keywords: ['query params parser', 'url search params', 'query string to json', 'json to query'],
    icon: '?=',
    component: 'QueryParamsParser',
    new: true,
    relatedSlugs: ['url-encoder', 'curl-fetch-converter', 'data-format-converter'],
    faq: [
      { q: 'Can I convert JSON back into a query string?', a: 'Yes. This tool works both ways so you can parse a URL or generate a fresh query string from JSON input.' },
    ],
  },
  {
    slug: 'contrast-checker',
    category: 'developer',
    name: 'WCAG Contrast Checker',
    tagline: 'Test text and background colors for accessibility compliance',
    description: 'Free online WCAG contrast checker. Test foreground and background color pairs, review AA and AAA accessibility thresholds, and preview a real UI block instantly.',
    h1: 'WCAG Contrast Checker Tool',
    metaTitle: 'Contrast Checker Online – WCAG AA & AAA Color Test',
    metaDescription: 'Check color contrast online against WCAG AA and AAA standards. Preview text pairs and accessibility pass or fail states instantly.',
    keywords: ['contrast checker', 'wcag contrast', 'accessibility color checker', 'aa aaa checker'],
    icon: '◐',
    component: 'ContrastChecker',
    new: true,
    popular: true,
    relatedSlugs: ['color-converter', 'css-gradient-generator', 'svg-optimizer'],
    faq: [
      { q: 'What contrast ratio passes WCAG AA?', a: 'For normal body text, WCAG AA requires a contrast ratio of at least 4.5:1. Large text can pass at 3:1.' },
    ],
  },
  {
    slug: 'css-gradient-generator',
    category: 'developer',
    name: 'CSS Gradient Generator',
    tagline: 'Create layered gradients and copy production-ready CSS',
    description: 'Free online CSS gradient generator. Pick colors, tune the angle, preview the gradient instantly, and copy the final CSS background declaration.',
    h1: 'CSS Gradient Generator (Free Online)',
    metaTitle: 'CSS Gradient Generator Online – Copy Gradient CSS',
    metaDescription: 'Generate modern linear gradients online, adjust colors and angle, and copy ready-to-use CSS instantly. Free and browser-based.',
    keywords: ['css gradient generator', 'linear gradient css', 'gradient maker', 'css background gradient'],
    icon: '🌈',
    component: 'CSSGradientGenerator',
    new: true,
    relatedSlugs: ['color-converter', 'contrast-checker', 'html-viewer'],
    faq: [
      { q: 'What CSS does this tool generate?', a: 'It outputs a copy-ready linear-gradient declaration you can drop directly into a CSS background rule.' },
    ],
  },
  {
    slug: 'svg-optimizer',
    category: 'image',
    name: 'SVG Optimizer',
    tagline: 'Optimize and format SVG markup for cleaner frontend assets',
    description: 'Free online SVG optimizer and formatter. Remove unnecessary metadata, clean markup, and prepare SVG assets for UI, docs, and frontend delivery.',
    h1: 'SVG Optimizer & Formatter',
    metaTitle: 'SVG Optimizer Online – Clean and Format SVG Markup',
    metaDescription: 'Optimize SVG markup online by removing metadata and formatting the output for cleaner frontend assets. Free and browser-based.',
    keywords: ['svg optimizer', 'svg formatter', 'clean svg', 'minify svg online'],
    icon: '⬡',
    component: 'SVGOptimizer',
    new: true,
    relatedSlugs: ['image-to-base64', 'color-converter', 'html-viewer'],
    faq: [
      { q: 'What does SVG optimization remove?', a: 'This tool strips common metadata and whitespace so SVG markup is easier to ship and maintain.' },
    ],
  },
  {
    slug: 'image-to-base64',
    category: 'image',
    name: 'Image to Base64',
    tagline: 'Convert image files into raw Base64 or full Data URI output',
    description: 'Free online image to Base64 converter. Upload an image, preview it instantly, and copy either the raw Base64 string or the full Data URI for embeds.',
    h1: 'Image to Base64 Converter (Free Online)',
    metaTitle: 'Image to Base64 Online – Copy Base64 or Data URI',
    metaDescription: 'Convert images to Base64 or Data URI directly in the browser. Great for embeds, prototypes, and frontend asset workflows.',
    keywords: ['image to base64', 'data uri generator', 'base64 image converter', 'image data uri'],
    icon: '🖼️',
    component: 'ImageToBase64',
    new: true,
    relatedSlugs: ['base64-encode', 'svg-optimizer', 'background-remover'],
    faq: [
      { q: 'What is the difference between Base64 and a Data URI?', a: 'Base64 is just the encoded content, while a Data URI also includes the MIME type prefix needed for direct embedding.' },
    ],
  },
  {
    slug: 'package-json-explorer',
    category: 'developer',
    name: 'Package.json Explorer',
    tagline: 'Inspect scripts, dependencies, and install commands instantly',
    description: 'Free online package.json explorer. Paste package metadata to inspect scripts, dependencies, devDependencies, and copy install commands by package manager.',
    h1: 'Package.json Explorer Tool (Free Online)',
    metaTitle: 'Package.json Explorer – Inspect Scripts & Dependencies',
    metaDescription: 'Paste any package.json file to inspect scripts, dependency groups, and install commands. Useful for npm, pnpm, and Yarn workflows.',
    keywords: ['package json viewer', 'package json explorer', 'npm package json', 'pnpm dependencies'],
    icon: '📦',
    component: 'PackageJsonExplorer',
    new: true,
    relatedSlugs: ['json-formatter', 'code-formatter', 'uuid-generator'],
    faq: [
      { q: 'Why use a package.json explorer?', a: 'It helps teams quickly inspect scripts, dependency groups, and reusable install commands without opening an IDE or terminal.' },
    ],
  },
  {
    slug: 'ci-matrix-generator',
    category: 'developer',
    name: 'CI Matrix Generator',
    tagline: 'Build GitHub Actions job matrices for Node, OS, and package managers',
    description: 'Free online CI matrix generator. Create copy-ready GitHub Actions matrices for Node.js versions, operating systems, and package manager combinations.',
    h1: 'CI Matrix Generator (GitHub Actions)',
    metaTitle: 'CI Matrix Generator – GitHub Actions Matrix Builder',
    metaDescription: 'Build GitHub Actions matrices for Node versions, operating systems, and package managers. Copy clean YAML-ready output instantly.',
    keywords: ['ci matrix generator', 'github actions matrix', 'node ci matrix', 'yaml matrix builder'],
    icon: '🛠️',
    component: 'CIMatrixBuilder',
    new: true,
    relatedSlugs: ['json-formatter', 'package-json-explorer', 'timestamp-converter'],
    faq: [
      { q: 'What is a CI matrix?', a: 'A CI matrix runs the same workflow across multiple operating systems, runtimes, or configurations so you can test broader compatibility.' },
    ],
  },
  {
    slug: 'prompt-template-builder',
    category: 'text',
    name: 'Prompt Template Builder',
    tagline: 'Structure AI-ready prompts with context, constraints, and output rules',
    description: 'Free online prompt template builder for AI developer workflows. Assemble task, context, constraints, examples, and output format into a reusable master prompt.',
    h1: 'Prompt Template Builder for AI Developer Workflows',
    metaTitle: 'Prompt Template Builder – Create Reusable AI Prompts',
    metaDescription: 'Build reusable AI prompts with sections for task, context, constraints, examples, and output format. Ideal for AI developer workflows.',
    keywords: ['prompt builder', 'ai prompt template', 'developer prompt builder', 'master prompt generator'],
    icon: '🤖',
    component: 'PromptTemplateBuilder',
    new: true,
    popular: true,
    relatedSlugs: ['markdown-previewer', 'json-formatter', 'code-formatter'],
    faq: [
      { q: 'Why use a structured prompt template?', a: 'A structured prompt keeps instructions reusable and consistent across repeated AI-assisted development tasks.' },
    ],
  },
  {
    slug: 'ai-chat-workbench',
    category: 'developer',
    name: 'AI Chat Workbench',
    tagline: 'Chat with LemonfoxAI for drafts, explanations, and technical help',
    description: 'AI chat workbench powered by LemonfoxAI. Generate content, refine developer copy, explain code, and get practical workflow help inside DevBoosty.',
    h1: 'AI Chat Workbench',
    metaTitle: 'AI Chat Workbench – LemonfoxAI Assistant for Developers',
    metaDescription: 'Use LemonfoxAI chat inside DevBoosty to draft copy, explain technical issues, and accelerate developer workflows.',
    keywords: ['ai chat tool', 'developer ai assistant', 'llm workbench', 'lemonfox chat'],
    icon: '◎',
    component: 'AIChatWorkbench',
    new: true,
    popular: true,
    relatedSlugs: ['prompt-template-builder', 'speech-to-text', 'text-to-speech'],
    faq: [
      { q: 'What can I use the AI chat workbench for?', a: 'It works well for product copy drafts, technical explanations, prompt rewrites, README help, and developer workflow support.' },
    ],
  },
  {
    slug: 'speech-to-text',
    category: 'developer',
    name: 'Speech to Text',
    tagline: 'Transcribe audio files and public audio URLs with AI',
    description: 'Speech-to-text tool powered by LemonfoxAI. Upload audio or pass a public audio URL to generate transcripts, captions, or structured transcription output quickly.',
    h1: 'Speech to Text Tool',
    metaTitle: 'Speech to Text Online – LemonfoxAI Transcription Tool',
    metaDescription: 'Transcribe audio files and URLs into text with LemonfoxAI speech recognition inside DevBoosty.',
    keywords: ['speech to text', 'audio transcription', 'ai transcript tool', 'whisper alternative'],
    icon: '🎙️',
    component: 'SpeechToTextTool',
    new: true,
    popular: true,
    relatedSlugs: ['text-to-speech', 'ai-chat-workbench', 'markdown-previewer'],
    faq: [
      { q: 'Can I transcribe a file or a URL?', a: 'Yes. You can either upload an audio file directly or pass a public audio URL to the transcription route.' },
    ],
  },
  {
    slug: 'text-to-speech',
    category: 'developer',
    name: 'Text to Speech',
    tagline: 'Turn text into downloadable AI voice output',
    description: 'Text-to-speech tool powered by LemonfoxAI. Convert text into natural speech, preview the audio, and download it in multiple audio formats.',
    h1: 'Text to Speech Tool',
    metaTitle: 'Text to Speech Online – LemonfoxAI Voice Generator',
    metaDescription: 'Generate speech from text with LemonfoxAI voices, preview audio, and download the result in DevBoosty.',
    keywords: ['text to speech', 'ai voice generator', 'tts tool', 'speech api'],
    icon: '🔊',
    component: 'TextToSpeechStudio',
    new: true,
    relatedSlugs: ['speech-to-text', 'ai-chat-workbench', 'prompt-template-builder'],
    faq: [
      { q: 'What can I use text-to-speech for?', a: 'It is useful for narration, accessibility previews, product demos, video voiceovers, and spoken documentation clips.' },
    ],
  },
  {
    slug: 'ai-image-generator',
    category: 'image',
    name: 'AI Image Generator',
    tagline: 'Generate illustrations, graphics, and product visuals from prompts',
    description: 'AI image generator powered by LemonfoxAI. Create concept art, social graphics, thumbnails, and UI visuals from text prompts in seconds.',
    h1: 'AI Image Generator',
    metaTitle: 'AI Image Generator Online – LemonfoxAI SDXL Tool',
    metaDescription: 'Generate images from prompts with LemonfoxAI inside DevBoosty. Great for thumbnails, graphics, concepts, and product visuals.',
    keywords: ['ai image generator', 'sdxl api tool', 'text to image', 'lemonfox image generation'],
    icon: '🪄',
    component: 'AIImageGenerator',
    new: true,
    popular: true,
    relatedSlugs: ['background-remover', 'image-enhancer', 'prompt-template-builder'],
    faq: [
      { q: 'What kind of images can I generate?', a: 'You can generate hero visuals, illustrations, thumbnails, concept art, and other prompt-driven graphics.' },
    ],
  },
];

// ── CATEGORY METADATA ─────────────────────────────────────────────────────────
export const CATEGORIES: Record<ToolCategory, {
  name: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  icon: string;
  color: string;
}> = {
  developer: {
    name: 'Developer Tools',
    description: 'JSON, Base64, HTML, URL, JWT and more tools for developers',
    metaTitle: 'Free Online Developer Tools – JSON, Base64, HTML & More',
    metaDescription: 'Free online developer tools including JSON formatter, Base64 encoder, HTML viewer, URL encoder, JWT decoder, and regex tester.',
    icon: '⚙️',
    color: 'from-blue-500 to-cyan-500',
  },
  text: {
    name: 'Text Tools',
    description: 'Word counter, case converter, and text manipulation tools',
    metaTitle: 'Free Online Text Tools – Word Counter, Case Converter & More',
    metaDescription: 'Free online text tools: word counter, case converter, remove line breaks, text sorter, and duplicate line remover.',
    icon: '📝',
    color: 'from-emerald-500 to-teal-500',
  },
  seo: {
    name: 'SEO Tools',
    description: 'Meta tag generator, keyword checker, slug generator & more',
    metaTitle: 'Free Online SEO Tools – Meta Tags, Keywords & Slug Generator',
    metaDescription: 'Free SEO tools: meta tag generator, keyword density checker, slug generator, and robots.txt generator.',
    icon: '🔍',
    color: 'from-orange-500 to-amber-500',
  },
  image: {
    name: 'Image Tools',
    description: 'Compress, convert, and resize images online for free',
    metaTitle: 'Free Online Image Tools – Compress, Convert & Resize Images',
    metaDescription: 'Free image tools: image compressor, JPG to PNG, PNG to WebP converter, and image resizer.',
    icon: '🖼️',
    color: 'from-purple-500 to-pink-500',
  },
  pdf: {
    name: 'PDF Tools',
    description: 'Merge, split, compress, and convert PDF files online',
    metaTitle: 'Free Online PDF Tools – Merge, Split & Compress PDFs',
    metaDescription: 'Free PDF tools: PDF merger, splitter, compressor, and PDF to Word converter. No signup required.',
    icon: '📄',
    color: 'from-red-500 to-rose-500',
  },
  converter: {
    name: 'Converter Tools',
    description: 'Unit converters: cm↔inch, kg↔lbs, Celsius↔Fahrenheit',
    metaTitle: 'Free Online Unit Converters – cm, kg, Temperature & More',
    metaDescription: 'Free unit converters: cm to inches, kg to lbs, Celsius to Fahrenheit. Accurate, instant, and no signup required.',
    icon: '🔄',
    color: 'from-indigo-500 to-violet-500',
  },
};

export const WORKSPACE_CATEGORIES: Record<WorkspaceCategory, {
  name: string;
  shortName: string;
  description: string;
  icon: string;
  color: string;
  badgeClassName: string;
}> = {
  'frontend-tools': {
    name: 'Frontend Tools',
    shortName: 'Frontend',
    description: 'Format UI code, preview markup, and ship cleaner front-end snippets.',
    icon: '</>',
    color: 'from-sky-500 via-cyan-500 to-teal-500',
    badgeClassName: 'border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-500/30 dark:bg-sky-500/10 dark:text-sky-200',
  },
  'backend-api': {
    name: 'Backend & API Tools',
    shortName: 'Backend & API',
    description: 'Inspect payloads, encode values, and prepare API-friendly data quickly.',
    icon: '{ }',
    color: 'from-emerald-500 via-teal-500 to-green-600',
    badgeClassName: 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200',
  },
  'devops-ci-cd': {
    name: 'DevOps & CI/CD Tools',
    shortName: 'DevOps',
    description: 'Build config snippets and workflow matrices for repeatable delivery pipelines.',
    icon: '⚙️',
    color: 'from-orange-500 via-amber-500 to-yellow-500',
    badgeClassName: 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200',
  },
  testing: {
    name: 'Testing Tools',
    shortName: 'Testing',
    description: 'Debug matching logic and validate tricky input patterns before shipping.',
    icon: '🧪',
    color: 'from-violet-500 via-fuchsia-500 to-pink-500',
    badgeClassName: 'border-fuchsia-200 bg-fuchsia-50 text-fuchsia-700 dark:border-fuchsia-500/30 dark:bg-fuchsia-500/10 dark:text-fuchsia-200',
  },
  'code-editors-ide': {
    name: 'Code Editors & IDE',
    shortName: 'Editors & IDE',
    description: 'Draft docs, preview Markdown, and clean source snippets in one place.',
    icon: '⌘',
    color: 'from-indigo-500 via-blue-500 to-sky-500',
    badgeClassName: 'border-indigo-200 bg-indigo-50 text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-500/10 dark:text-indigo-200',
  },
  'package-managers': {
    name: 'Package Managers',
    shortName: 'Packages',
    description: 'Inspect dependencies and generate install commands for npm, pnpm, and Yarn.',
    icon: '📚',
    color: 'from-cyan-500 via-sky-500 to-blue-600',
    badgeClassName: 'border-cyan-200 bg-cyan-50 text-cyan-700 dark:border-cyan-500/30 dark:bg-cyan-500/10 dark:text-cyan-200',
  },
  'ui-ux-design': {
    name: 'UI/UX & Design Tools',
    shortName: 'UI/UX',
    description: 'Prepare visuals, generate palettes, and clean creative assets faster.',
    icon: '✦',
    color: 'from-rose-500 via-pink-500 to-orange-400',
    badgeClassName: 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-200',
  },
  'performance-seo': {
    name: 'Performance & SEO Tools',
    shortName: 'Performance & SEO',
    description: 'Optimize assets, generate SEO metadata, and tighten technical discoverability.',
    icon: '🚀',
    color: 'from-lime-500 via-emerald-500 to-teal-500',
    badgeClassName: 'border-lime-200 bg-lime-50 text-lime-700 dark:border-lime-500/30 dark:bg-lime-500/10 dark:text-lime-200',
  },
  security: {
    name: 'Security Tools',
    shortName: 'Security',
    description: 'Inspect tokens, generate strong credentials, and handle sensitive values safely.',
    icon: '🔐',
    color: 'from-slate-700 via-slate-900 to-black',
    badgeClassName: 'border-slate-300 bg-slate-100 text-slate-700 dark:border-slate-600 dark:bg-slate-800/60 dark:text-slate-200',
  },
  'ai-developer': {
    name: 'AI Developer Tools',
    shortName: 'AI Dev',
    description: 'Build reusable prompt workflows and AI-ready task templates for development teams.',
    icon: '◎',
    color: 'from-purple-500 via-pink-500 to-rose-500',
    badgeClassName: 'border-purple-200 bg-purple-50 text-purple-700 dark:border-purple-500/30 dark:bg-purple-500/10 dark:text-purple-200',
  },
};

const WORKSPACE_CATEGORY_BY_SLUG: Record<string, WorkspaceCategory> = {
  'json-formatter': 'backend-api',
  'json-minify': 'backend-api',
  'base64-encode': 'backend-api',
  'html-viewer': 'code-editors-ide',
  'html-formatter': 'frontend-tools',
  'url-encoder': 'backend-api',
  'jwt-decoder': 'security',
  'regex-tester': 'testing',
  'word-counter': 'code-editors-ide',
  'case-converter': 'code-editors-ide',
  'remove-line-breaks': 'code-editors-ide',
  'text-sorter': 'code-editors-ide',
  'duplicate-line-remover': 'code-editors-ide',
  'meta-tag-generator': 'performance-seo',
  'keyword-density': 'performance-seo',
  'slug-generator': 'performance-seo',
  'robots-txt-generator': 'performance-seo',
  'image-compressor': 'performance-seo',
  'jpg-to-png': 'ui-ux-design',
  'png-to-webp': 'ui-ux-design',
  'image-resizer': 'ui-ux-design',
  'pdf-merge': 'code-editors-ide',
  'pdf-split': 'code-editors-ide',
  'pdf-compressor': 'code-editors-ide',
  'pdf-to-word': 'code-editors-ide',
  'cm-to-inch': 'ui-ux-design',
  'kg-to-lbs': 'ui-ux-design',
  'celsius-to-fahrenheit': 'ui-ux-design',
  'timestamp-converter': 'backend-api',
  'password-generator': 'security',
  'uuid-generator': 'backend-api',
  'lorem-ipsum-generator': 'ui-ux-design',
  'number-base-converter': 'backend-api',
  'html-entity-encoder': 'frontend-tools',
  'css-minifier': 'frontend-tools',
  'js-minifier': 'frontend-tools',
  'color-converter': 'ui-ux-design',
  'background-remover': 'ui-ux-design',
  'image-enhancer': 'ui-ux-design',
  'markdown-previewer': 'code-editors-ide',
  'code-formatter': 'frontend-tools',
  'data-format-converter': 'backend-api',
  'json-diff': 'testing',
  'text-diff': 'testing',
  'hash-generator': 'security',
  'hmac-generator': 'security',
  'curl-fetch-converter': 'backend-api',
  'query-params-parser': 'backend-api',
  'contrast-checker': 'ui-ux-design',
  'css-gradient-generator': 'ui-ux-design',
  'svg-optimizer': 'frontend-tools',
  'image-to-base64': 'frontend-tools',
  'package-json-explorer': 'package-managers',
  'ci-matrix-generator': 'devops-ci-cd',
  'prompt-template-builder': 'ai-developer',
  'ai-chat-workbench': 'ai-developer',
  'speech-to-text': 'ai-developer',
  'text-to-speech': 'ai-developer',
  'ai-image-generator': 'ai-developer',
};

const TOOLS: Tool[] = TOOL_DEFINITIONS.map((tool) => ({
  ...tool,
  workspaceCategory: WORKSPACE_CATEGORY_BY_SLUG[tool.slug] ?? 'backend-api',
}));

// ── HELPERS ───────────────────────────────────────────────────────────────────
export function getAllTools(): Tool[] {
  return TOOLS;
}

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter(t => t.category === category);
}

export function getToolsByWorkspaceCategory(category: WorkspaceCategory): Tool[] {
  return TOOLS.filter((tool) => tool.workspaceCategory === category);
}

export function getRelatedTools(tool: Tool): Tool[] {
  if (!tool.relatedSlugs?.length) {
    return TOOLS.filter((item) => item.workspaceCategory === tool.workspaceCategory && item.slug !== tool.slug).slice(0, 4);
  }
  return tool.relatedSlugs
    .map(slug => TOOLS.find(t => t.slug === slug))
    .filter(Boolean) as Tool[];
}

export function getPopularTools(): Tool[] {
  return [...TOOLS].reverse().filter((tool) => tool.popular);
}

export function getNewTools(): Tool[] {
  return [...TOOLS].reverse().filter((tool) => tool.new);
}
